
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author AllienWare
 */
import java.sql.*;

public class Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */
    Connection conn;
    Error err;
    String path, cad, url;
    PreparedStatement pstm;
    ResultSet res;
    nuevocliente nclient;
    eliminarcliente delcl;
    ModificarCliente modcl;
    String idlog;
    DefaultListModel compras;
    DefaultListModel rentas;
    Lista lis;
    float total;
    void conexion(String inf) {
        try {
            cad = inf;
            path = System.getProperty("user.dir");
            path += "\\videoclub.accdb";
            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");

            System.out.println(path);
            url = "jdbc:odbc:Driver={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=" + path;
            conn = DriverManager.getConnection(url);
            pstm = conn.prepareStatement(cad);
            res = pstm.executeQuery();

        } catch (Exception e) {
            System.out.println(e);
        }
    }
    DefaultListModel model = new DefaultListModel();

    public Usuario() {
        initComponents();
        list.setModel(model);
        nclient = new nuevocliente();
        delcl = new eliminarcliente();
        modcl = new ModificarCliente();
        err = new Error();
        compras=new DefaultListModel();
        this.setLocationRelativeTo(null);
        lis=new Lista();
        rentas=new DefaultListModel();
        total=0;
        entregar.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        entregar = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        entregaid = new javax.swing.JTextField();
        entregabtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        rtitulo = new javax.swing.JRadioButton();
        rid = new javax.swing.JRadioButton();
        lblarticulo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList();
        lblcliente = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        entregar.setTitle("Artículo a entregar");
        entregar.setMinimumSize(new java.awt.Dimension(400, 173));
        entregar.setResizable(false);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel12.setText("ID:");

        entregaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entregaidActionPerformed(evt);
            }
        });

        entregabtn.setText("Aceptar");
        entregabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entregabtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(entregaid, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(entregabtn)
                        .addGap(150, 150, 150))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entregaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(entregabtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout entregarLayout = new javax.swing.GroupLayout(entregar.getContentPane());
        entregar.getContentPane().setLayout(entregarLayout);
        entregarLayout.setHorizontalGroup(
            entregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        entregarLayout.setVerticalGroup(
            entregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        rtitulo.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rtitulo);
        rtitulo.setFont(new java.awt.Font("Eras Medium ITC", 0, 11)); // NOI18N
        rtitulo.setForeground(new java.awt.Color(51, 51, 51));
        rtitulo.setText("Titulo");

        rid.setBackground(new java.awt.Color(204, 204, 204));
        buttonGroup1.add(rid);
        rid.setFont(new java.awt.Font("Eras Medium ITC", 0, 11)); // NOI18N
        rid.setForeground(new java.awt.Color(51, 51, 51));
        rid.setSelected(true);
        rid.setText("Id");
        rid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ridActionPerformed(evt);
            }
        });

        lblarticulo.setBackground(new java.awt.Color(230, 230, 230));
        lblarticulo.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        lblarticulo.setForeground(new java.awt.Color(153, 153, 153));
        lblarticulo.setText("Ingresa Articulo...");
        lblarticulo.setToolTipText("Texto...");
        lblarticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblarticuloActionPerformed(evt);
            }
        });
        lblarticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblarticuloKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Eras Medium ITC", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shoppingcart32.png"))); // NOI18N
        jLabel8.setText("Comprar");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Eras Medium ITC", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boxdownload32.png"))); // NOI18N
        jLabel9.setText("Entregar");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Eras Medium ITC", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boxupload32.png"))); // NOI18N
        jLabel10.setText("Rentar");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Eras Medium ITC", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search32.png"))); // NOI18N
        jLabel11.setText("Buscar");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel11)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rid, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblarticulo)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblarticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rid)
                    .addComponent(rtitulo))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11))
                .addGap(57, 57, 57)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setBackground(new java.awt.Color(226, 226, 226));
        jLabel3.setFont(new java.awt.Font("Eras Light ITC", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Navegación");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Eras Light ITC", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(217, 217, 217));
        jLabel2.setText("MENU");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(226, 226, 226));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userplus32.png"))); // NOI18N
        jLabel5.setText("Nuevo Cliente");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(226, 226, 226));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/linedpaperpencil32.png"))); // NOI18N
        jLabel4.setText("Modificar Cliente");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel4.setVerifyInputWhenFocusTarget(false);
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(226, 226, 226));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userminus32.png"))); // NOI18N
        jLabel6.setText("Eliminar Cliente");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(226, 226, 226));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/questionbook32.png"))); // NOI18N
        jLabel7.setText("Entra cliente");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(121, 121, 121)
                .addComponent(jLabel6)
                .addGap(119, 119, 119)
                .addComponent(jLabel4)
                .addGap(104, 104, 104)
                .addComponent(jLabel7)
                .addGap(111, 111, 111))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Eras Light ITC", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(226, 226, 226));
        jLabel1.setText("Modo  Usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(391, 391, 391))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        list.setBackground(new java.awt.Color(249, 249, 216));
        jScrollPane1.setViewportView(list);

        lblcliente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Confirmar transacciones");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar transacciones");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.out.println(path);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void ridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ridActionPerformed

    boolean bandaux = true;
    private void lblarticuloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblarticuloKeyTyped
        // TODO add your handling code here:
        if (bandaux) {
            String cad = lblarticulo.getText();
            lblarticulo.setText("");
            bandaux = false;
        }
    }//GEN-LAST:event_lblarticuloKeyTyped

    private void lblarticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblarticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblarticuloActionPerformed

    boolean login = false;
    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        //click compra
        int i=0;
        boolean ban = true;
        String id, idc;
        if (login) {
            if (list.isSelectionEmpty()) {
                err.setMsg("Debes seleccionar un artículo");
                err.setVisible(true);
            } else {
                String seleccion = list.getSelectedValue().toString();
                id = "";
                char c;
                while ((c = seleccion.charAt(i)) != ' ') {
                    if(i>2)
                    {id += c;}
                    i++;
                }
                conexion("SELECT * FROM articulos");
                try {
                    while (res.next() && ban) {
                        idc = res.getString("Id");
                        if (id.equals(idc)) {
                            int cant=Integer.parseInt(res.getString("cantcompra"));
                            if(cant>0){
                                float pc=Float.parseFloat(res.getString("costcompra"));
                                compras.addElement("ID:"+id+"     $"+pc);
                                lis.setmodl(compras, pc);
                                total+=pc;
                                lis.setVisible(true);
                            }else{
                                err.setMsg("No hay articulos disponibles");
                                err.setVisible(true);
                            }
                            ban=false;
                        }
                    }

                } catch (Exception w) {
                    System.err.println(w);
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se ha ingresado cliente");
        }
    }//GEN-LAST:event_jLabel8MouseClicked


    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        //click consulta
        String y = lblarticulo.getText();
        DefaultListModel m = new DefaultListModel();
        conexion("SELECT articulos.Id, articulos.titulo, articulos.costcompra, articulos.cantcompra, articulos.costrenta, articulos.cantrenta FROM articulos");
        String s;
        if (rid.isSelected()) {
            try {
                while (res.next()) {
                    String x = res.getString("Id");
                    if (x.toUpperCase().contains(y.toUpperCase())) {
                        String t = res.getString("titulo");
                        String pc = res.getString("costcompra");
                        String cc = res.getString("cantcompra");
                        String pr = res.getString("costrenta");
                        String cr = res.getString("cantrenta");
                        s = "Id:" + x + "     Titulo:" + t + "     Precio de compra:" + pc + "     Cantidad para compra:" + cc + "     Precio de renta:" + pr + "     Cantidad para renta:" + cr;
                        m.addElement(s);
                    }

                }
                list.setModel(m);
                conn.close();
            } catch (Exception e) {
                System.err.println(e);
            }
        } else if (rtitulo.isSelected()) {
            try {
                while (res.next()) {
                    String t = res.getString("titulo");
                    if (t.toUpperCase().contains(y.toUpperCase())) {
                        String x = res.getString("Id");
                        String pc = res.getString("costcompra");
                        String cc = res.getString("cantcompra");
                        String pr = res.getString("costrenta");
                        String cr = res.getString("cantrenta");
                        s = "Id:" + x + "     Titulo:" + t + "     Precio de compra:" + pc + "     Cantidad para compra:" + cc + "     Precio de renta:" + pr + "     Cantidad para renta:" + cr;
                        m.addElement(s);
                    }

                }
                list.setModel(m);
                conn.close();
            } catch (Exception e) {
                System.err.println(e);
            }
        } else {
            err.setMsg("Debes seleccionar ID o Titulo");
            try {
                conn.close();
            } catch (Exception e) {
                System.err.println(e);
            }
            err.setVisible(true);
        }

    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        int i=0;
        boolean ban = true;
        String id, idc;
        if (login) {
            if (list.isSelectionEmpty()) {
                err.setMsg("Debes seleccionar un artículo");
                err.setVisible(true);
            } else {
                String seleccion = list.getSelectedValue().toString();
                id = "";
                char c;
                while ((c = seleccion.charAt(i)) != ' ') {
                    if(i>2)
                    {id += c;}
                    i++;
                }
                conexion("SELECT * FROM articulos");
                try {
                    while (res.next() && ban) {
                        idc = res.getString("Id");
                        if (id.equals(idc)) {
                            int cant=Integer.parseInt(res.getString("cantrenta"));
                            if(cant>0){
                                float pc=Float.parseFloat(res.getString("costrenta"));
                                rentas.addElement("ID:"+id+"     $"+pc);
                                lis.setmodl2(rentas, pc);
                                total+=pc;
                                lis.setVisible(true);
                            }else{
                                err.setMsg("No hay articulos disponibles");
                                err.setVisible(true);
                            }
                            ban=false;
                        }
                    }

                } catch (Exception w) {
                    System.err.println(w);
                }
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se ha ingresado cliente");
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        if (login) {
            entregar.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(rootPane, "No se ha ingresado cliente");
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        // intenta ingresar cliente
        String x, info = "";
        boolean ban = true;
        String cliente = JOptionPane.showInputDialog("Ingrese id");
        conexion("SELECT * FROM clientes");
        try {
            while (res.next() && ban) {
                x = res.getString("Id");
                if (cliente.equals(x)) {
                    idlog = x;
                    info = res.getString("nombre");
                    ban = false;
                }
            }
            conn.close();
        } catch (Exception r) {
            System.err.println(r);
        }
        if (ban) {
            err.setMsg("ID no encontrada");
            err.setVisible(true);
        } else {
            lblcliente.setText("Cliente: " + info);
            login = true;
        }
        //si cliente existe

        //sino
        //mensaje error, no existe cliente
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        nclient.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        delcl.setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        modcl.setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Main m = new Main();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        conexion("SELECT * FROM articulos");
        String id, idc;
        int cc, cr;
        try{
            while(res.next()){
                idc=res.getString("Id");
                cc=Integer.parseInt(res.getString("cantcompra"));
                cr=Integer.parseInt(res.getString("cantrenta"));
                for (int i = 0; i < compras.getSize(); i++) {
                    String seleccion = compras.get(i).toString();
                    id = "";
                    char c;
                    while ((c = seleccion.charAt(i)) != ' ') {
                        if(i>2)
                        {id += c;}
                        i++;
                    }
                    if(idc.equals(id)){
                        cc--;
                    }
                }
                for (int i = 0; i < rentas.getSize(); i++) {
                    String seleccion = rentas.get(i).toString();
                    id = "";
                    char c;
                    while ((c = seleccion.charAt(i)) != ' ') {
                        if(i>2)
                        {id += c;}
                        i++;
                    }
                    if(idc.equals(id)){
                        cr--;
                    }
                }
                conexion("UPDATE articulos SET cantcompra='"+cc+"', cantrenta='"+cr+"' WHERE Id='"+idc+"'");
                conn.close();
            }
            
           
            
        }catch (Exception d){
            System.err.println(d);
        }
        total=0;
        compras=new DefaultListModel();
        rentas=new DefaultListModel();
        lis.reset();
        lis.dispose();
        login=false;
        lblcliente.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        total=0;
        compras=new DefaultListModel();
        rentas=new DefaultListModel();
        lis.reset();
        lis.dispose();
        login=false;
        lblcliente.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void entregaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entregaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entregaidActionPerformed

    private void entregabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entregabtnActionPerformed
        // TODO add your handling code here:
        String ide=entregaid.getText();
        if(ide.isEmpty()){
            err.setMsg("Debes ingresar la ID");
            err.setVisible(true);
        }else{
            conexion("SELECT * FROM articulos");
        String id;
        boolean ban=true;
        int  cr=0;
        try{
            while(res.next() && ban){
                id=res.getString("Id");
                if(id.equals(ide)){
                    cr=Integer.parseInt(res.getString("cantrenta"));
                    cr++;
                    ban=false;
                }
            }
            if(ban){
                err.setMsg("ID no encontrada");
                err.setVisible(true);
            }else{
                conexion("UPDATE articulos SET  cantrenta='"+cr+"' WHERE Id='"+ide+"'");
            }
            conn.close();
        }catch(Exception j){
            System.err.println(j);
        }
        entregaid.setText("");
        entregar.setVisible(false);
        }
    }//GEN-LAST:event_entregabtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton entregabtn;
    private javax.swing.JTextField entregaid;
    private javax.swing.JDialog entregar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lblarticulo;
    private javax.swing.JLabel lblcliente;
    private javax.swing.JList list;
    private javax.swing.JRadioButton rid;
    private javax.swing.JRadioButton rtitulo;
    // End of variables declaration//GEN-END:variables
}
